baseURL = "https://languages-in-floss.eu"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

title = "Languages in FLOSS"

theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = false

[params.info]
description = "Natural languages support"
title404 = "We can't find this page, wrong URL?"

[params.assets]
favicon = "favicon.ico"
#customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "CC-BY SA 3.0"
holder = "Languages in FLOSS"
startYear = "2020"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","languages","sidebar_menu","taxonomy_cloud", "search"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.comments]
enable = true

[params.social]
email = "contact@languages-in-floss.eu"
github = "languages-in-floss"
mastodon = "https://mamot.fr/@languages_in_floss"

[params.search]
client = "fuse"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.fr]
lang = "fr"
contentDir = "content/fr"
languageName = "Français"
weight = 1

[languages.oc]
lang = "oc"
contentDir = "translations/oc"
languageName = "Occitan"
weight = 1

[languages.ar]
lang = "ar"
contentDir = "translations/ar"
languageName = "العربية"
weight = 1
LanguageDirection = "rtl"
