baseURL = "https://languages-in-floss.eu"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

title = "Langues et logiciels libres"

theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = false

[params.info]
description = "Partages et aventures"
title404 = "We can't find this page, wrong URL?"

[params.assets]
favicon = "favicon.ico"
#customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "CC-BY SA 4.0"
holder = "Languages in FLOSS"
startYear = "2020"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","languages","sidebar_menu","taxonomy_cloud", "search"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.comments]
enable = true

[params.social]
email = "contact@languages-in-floss.eu"
github = "languages-in-floss"
mastodon = "https://mastodon.languages-in-floss.eu/@contact"

[params.search]
client = "fuse"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:title/"
posts = "/:year/:month/:title/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.fr]
contentDir = "content/fr"
languageName = "Français"
weight = 1

[languages.fr.params]
lang = "fr"

[languages.oc]
contentDir = "content-translated/oc"
languageName = "Occitan"
title = "Lengas e logicials liures"
weight = 1

[languages.oc.params]
lang = "oc"

[languages.oc.params.info]
description = "partatge e aventuras"

[languages.ar]
lang = "ar"
contentDir = "content-translated/ar"
languageName = "العربية"
title = "لغات وبرمجيات حرة"
weight = 1
LanguageDirection = "rtl"

[languages.ar.params]
lang = "ar"

[languages.ar.params.info]
description = "مشاركات و مغامرات"

[languages.pt_BR]
contentDir = "content-translated/pt_BR"
languageName = "Português (Brazil)"
title = "Idiomas e software livre"
weight = 1

[languages.pt_BR.params]
lang = "pt_BR"

[languages.pt_BR.params.info]
description = "Desafios e aventuras"
title404 = "Não encontramos esta página, URL incorreta?"

[languages.pt_PT]
contentDir = "content-translated/pt_PT"
languageName = "Português (Portugal)"
weight = 1

[languages.pt_PT.params]
lang = "pt_PT"

[languages.pt_PT.params.info]
description = "Desafios e aventuras"
title404 = "Não encontramos esta página, URL incorreta?"

[languages.pl]
contentDir = "content-translated/pl"
languageName = "Polski (Polish)"
title = "Języki i wolne oprogramowanie"
weight = 1

[languages.pl.params]
lang = "pl"

[languages.pl.params.info]
description = "Dzielenie się i przygody"
title404 = "Nie możemy znaleźć tej strony, zły adres URL?"

[languages.uk]
contentDir = "content-translated/uk"
languageName = "Українська (Ukrainian)"
title = "Вільні мови та логіка"
weight = 1

[languages.uk.params]
lang = "uk"

[languages.uk.params.info]
description = "Спільне використання та пригоди"
title404 = "Ми не можемо знайти цю сторінку, невірна URL-адреса?"

[languages.bn]
contentDir = "content-translated/bn"
languageName = "বাংলা (Bengali)"
title = "ভাষা এবং বিনামূল্যের সফটওয়্যার"
weight = 1

[languages.bn.params]
lang = "bn"

[languages.bn.params.info]
description = "শেয়ার এবং অ্যাডভেঞ্চার"
title404 = "আমরা এই পৃষ্ঠাটি খুঁজে পাচ্ছি না, ভুল URL?"

[languages.ca]
contentDir = "content-translated/ca"
languageName = "Català (Catalan)"
title = "Idiomes i programari lliure"
weight = 1

[languages.ca.params]
lang = "ca"

[languages.ca.params.info]
description = "Accions i aventures"
title404 = "No podem trobar aquesta pàgina, URL incorrecte?"

[languages.ko]
contentDir = "content-translated/ko"
languageName = "한국어 (Korean)"
title = "언어 및 무료 소프트웨어"
weight = 1

[languages.ko.params]
lang = "ko"

[languages.ko.params.info]
description = "공유 및 모험"
title404 = "이 페이지를 찾을 수 없습니다, URL이 잘못되었나요?"