title: Bahasa dan perangkat lunak bebas
languageName: Bahasa Indonesia (Indonesian)
params:
  info:
    description: Berbagi dan petualangan
    title404: Halaman ini tidak ditemukan, apakah URL-nya benar?
